/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAgentTraceAnalyzerRouteImport } from './routes/ai-agent-trace-analyzer'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as ApiIngestRouteImport } from './routes/api.ingest'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppRoastsRouteImport } from './routes/app.roasts'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as AppIntegrationsIndexRouteImport } from './routes/app.integrations.index'
import { Route as AppRoastsIndexRouteImport } from './routes/app.roasts.index'
import { Route as AppRoastsBatchRouteImport } from './routes/app.roasts.$batch'
import { Route as AppIntegrationsLangsmithNewRouteImport } from './routes/app.integrations.langsmith.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentTraceAnalyzerRoute = AiAgentTraceAnalyzerRouteImport.update({
  id: '/ai-agent-trace-analyzer',
  path: '/ai-agent-trace-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRoastsRoute = AppRoastsRouteImport.update({
  id: '/roasts',
  path: '/roasts',
  getParentRoute: () => AppRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIntegrationsRoute,
} as any)
const AppRoastsIndexRoute = AppRoastsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoastsRoute,
} as any)
const AppRoastsBatchRoute = AppRoastsBatchRouteImport.update({
  id: '/$batch',
  path: '/$batch',
  getParentRoute: () => AppRoastsRoute,
} as any)
const AppIntegrationsLangsmithNewRoute =
  AppIntegrationsLangsmithNewRouteImport.update({
    id: '/langsmith/new',
    path: '/langsmith/new',
    getParentRoute: () => AppIntegrationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent-trace-analyzer': typeof AiAgentTraceAnalyzerRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/ingest': typeof ApiIngestRoute
  '/app/integrations': typeof AppIntegrationsRouteWithChildren
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/roasts': typeof AppRoastsRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/roasts/$batch': typeof AppRoastsBatchRoute
  '/app/integrations/': typeof AppIntegrationsIndexRoute
  '/app/roasts/': typeof AppRoastsIndexRoute
  '/app/integrations/langsmith/new': typeof AppIntegrationsLangsmithNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent-trace-analyzer': typeof AiAgentTraceAnalyzerRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/ingest': typeof ApiIngestRoute
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/r/$slug': typeof RSlugRoute
  '/app': typeof AppIndexRoute
  '/app/roasts/$batch': typeof AppRoastsBatchRoute
  '/app/integrations': typeof AppIntegrationsIndexRoute
  '/app/roasts': typeof AppRoastsIndexRoute
  '/app/integrations/langsmith/new': typeof AppIntegrationsLangsmithNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent-trace-analyzer': typeof AiAgentTraceAnalyzerRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/update-password': typeof UpdatePasswordRoute
  '/api/ingest': typeof ApiIngestRoute
  '/app/integrations': typeof AppIntegrationsRouteWithChildren
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/roasts': typeof AppRoastsRouteWithChildren
  '/r/$slug': typeof RSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/roasts/$batch': typeof AppRoastsBatchRoute
  '/app/integrations/': typeof AppIntegrationsIndexRoute
  '/app/roasts/': typeof AppRoastsIndexRoute
  '/app/integrations/langsmith/new': typeof AppIntegrationsLangsmithNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent-trace-analyzer'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/update-password'
    | '/api/ingest'
    | '/app/integrations'
    | '/app/new'
    | '/app/profile'
    | '/app/roasts'
    | '/r/$slug'
    | '/app/'
    | '/app/roasts/$batch'
    | '/app/integrations/'
    | '/app/roasts/'
    | '/app/integrations/langsmith/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent-trace-analyzer'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/update-password'
    | '/api/ingest'
    | '/app/new'
    | '/app/profile'
    | '/r/$slug'
    | '/app'
    | '/app/roasts/$batch'
    | '/app/integrations'
    | '/app/roasts'
    | '/app/integrations/langsmith/new'
  id:
    | '__root__'
    | '/'
    | '/ai-agent-trace-analyzer'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/update-password'
    | '/api/ingest'
    | '/app/integrations'
    | '/app/new'
    | '/app/profile'
    | '/app/roasts'
    | '/r/$slug'
    | '/app/'
    | '/app/roasts/$batch'
    | '/app/integrations/'
    | '/app/roasts/'
    | '/app/integrations/langsmith/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentTraceAnalyzerRoute: typeof AiAgentTraceAnalyzerRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ApiIngestRoute: typeof ApiIngestRoute
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent-trace-analyzer': {
      id: '/ai-agent-trace-analyzer'
      path: '/ai-agent-trace-analyzer'
      fullPath: '/ai-agent-trace-analyzer'
      preLoaderRoute: typeof AiAgentTraceAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roasts': {
      id: '/app/roasts'
      path: '/roasts'
      fullPath: '/app/roasts'
      preLoaderRoute: typeof AppRoastsRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/integrations/': {
      id: '/app/integrations/'
      path: '/'
      fullPath: '/app/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
    '/app/roasts/': {
      id: '/app/roasts/'
      path: '/'
      fullPath: '/app/roasts/'
      preLoaderRoute: typeof AppRoastsIndexRouteImport
      parentRoute: typeof AppRoastsRoute
    }
    '/app/roasts/$batch': {
      id: '/app/roasts/$batch'
      path: '/$batch'
      fullPath: '/app/roasts/$batch'
      preLoaderRoute: typeof AppRoastsBatchRouteImport
      parentRoute: typeof AppRoastsRoute
    }
    '/app/integrations/langsmith/new': {
      id: '/app/integrations/langsmith/new'
      path: '/langsmith/new'
      fullPath: '/app/integrations/langsmith/new'
      preLoaderRoute: typeof AppIntegrationsLangsmithNewRouteImport
      parentRoute: typeof AppIntegrationsRoute
    }
  }
}

interface AppIntegrationsRouteChildren {
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppIntegrationsLangsmithNewRoute: typeof AppIntegrationsLangsmithNewRoute
}

const AppIntegrationsRouteChildren: AppIntegrationsRouteChildren = {
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppIntegrationsLangsmithNewRoute: AppIntegrationsLangsmithNewRoute,
}

const AppIntegrationsRouteWithChildren = AppIntegrationsRoute._addFileChildren(
  AppIntegrationsRouteChildren,
)

interface AppRoastsRouteChildren {
  AppRoastsBatchRoute: typeof AppRoastsBatchRoute
  AppRoastsIndexRoute: typeof AppRoastsIndexRoute
}

const AppRoastsRouteChildren: AppRoastsRouteChildren = {
  AppRoastsBatchRoute: AppRoastsBatchRoute,
  AppRoastsIndexRoute: AppRoastsIndexRoute,
}

const AppRoastsRouteWithChildren = AppRoastsRoute._addFileChildren(
  AppRoastsRouteChildren,
)

interface AppRouteChildren {
  AppIntegrationsRoute: typeof AppIntegrationsRouteWithChildren
  AppNewRoute: typeof AppNewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRoastsRoute: typeof AppRoastsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIntegrationsRoute: AppIntegrationsRouteWithChildren,
  AppNewRoute: AppNewRoute,
  AppProfileRoute: AppProfileRoute,
  AppRoastsRoute: AppRoastsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentTraceAnalyzerRoute: AiAgentTraceAnalyzerRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ApiIngestRoute: ApiIngestRoute,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
